# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 14:44
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('accounts', '0002_user_geoposition'),
	]

	operations = [
		migrations.AlterField(
			model_name='user',
			name='username',
			field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
		),
	]
